### ISSUE TITLE
Move prometheus-statsd-exporter to prometheus-community/helm-charts

### ISSUE THREAD

**Issue by acondrat** [niclic/helm-charts#3]
Hello and thanks for creating this helm chart!

There is a fairly new repo that is now home for most prometheus related charts - https://github.com/prometheus-community/helm-charts
I guess you could get more feedback and contributions if you move the chart there.

**Comment by niclic** [comment]
Sorry for the late response. I think this is probably a good idea, so I will get on it.

**Comment by niclic** [comment]
A different version of this chart was created in the [prometheus-community](https://github.com/prometheus-community/helm-charts) repo.

I have deprecated this one as there is no point in maintaining multiple versions of the same chart.
